name: Make Repository

on:
  push:
    branches:
      - master
      - debug
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time and date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
      
    - name: Add keyserver
      run:  mkdir ~/.gnupg && touch ~/.gnupg/gpg.conf && echo 'keyserver hkps://keys.openpgp.org' >> ~/.gnupg/gpg.conf 

    - name: Build Packages
      uses: kopp/build-aur-packages@v1
      with:
        packages: >
          adwsteamgtk
          binggpt-desktop-bin
          blanket-git
          cambalache
          deepin-wine-helper
          deepin-wine-wechat
          deepin-wine6-stable
          dotnet-cli-telemetry-optout-git
          exa-git
          firefox-gnome-theme-git
          geopard
          glfw-git
          gnome-shell-extension-alphabetical-grid-extension-git
          gnome-shell-extension-blur-my-shell-git
          gnome-shell-extension-customize-ibus
          gnome-shell-extension-just-perfection-desktop-git
          gnome-shell-extension-pano-git
          gnome-shell-extension-scroll-workspaces-git
          gnome-shell-extension-status-area-horizontal-spacing-git
          hardcode-tray-git
          harmonyos-sans-git
          i4tools-bin
          icu71
          icu72-bin
          jd-gui-bin
          lib32-udis86-git
          libhandy-git
          libldap24
          libre-menu-editor
          libuiohook
          linuxqq-nt-bwrap
          mathematica
          mcpelauncher-msa-ui-qt-git
          nautilus-open-any-terminal-git
          nbtexplorer
          nitch-git
          noto-fonts-cjk-sc-vf
          ns-usbloader
          nx-udev
          obs-freeze-filter
          obs-pipewire-audio-capture-bin
          obs-plugin-input-overlay-git
          osu-lazer-git
          osu-mime
          otf-monocraft
          pacman-log-orphans-hook
          phira-bin
          qqmusic-bin
          rockyou
          rslsync
          s
          shimo
          sif-git
          snapd-xdg-open-git
          the-honkers-railway-launcher-bin
          tlpui-git
          ttf-monocraft
          ttf-ms-win10
          ttf-ms-win10-zh_cn
          turbowarp-desktop-bin
          vencord-installer-bin
          vkd3d-proton-bin
          whatip-git
          xmind
          yt-dlp-drop-in

          
    - name: List generated Files
      run: ls -1 > ${{ github.workspace }}/files.txt
    - name: Remove the current data from the release
      uses: kopp/action-delete-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurci2
    - name: Upload Files to Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurci2
        name: Build ${{ github.run_number }} at ${{ steps.date.outputs.date }}
        files: |
          ${{ github.workspace }}/*
        draft: false
        prerelease: false
